#!/bin/bash
#/data/data/com.termux/files/usr/bin/bash

while :;
do clear
echo Realtime rates from Koinex
echo 
./koin |awk -F '"' '{print $4" : "$6"\n"$8" : "$10"\n"$16" : "$18"\n"$20" : "$22}' 
echo
echo  Marketcap info from  Coinmarketcap
echo
curl https://api.coinmarketcap.com/v1/global/
sleep 25
done
